name: Super-Linter

on:
  push:
    branches:
      - playground
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run ESLint on JavaScript and HTML files
        uses: super-linter/super-linter@v7.2.0
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_JS: true
          VALIDATE_HTML: true
          FILTER_REGEX_INCLUDE: "src/.*\\.(js|html)$" # Modify path if needed
