name: Playwright Tests
on:
  workflow_run:
    workflows:
      - Deploy
    types:
      - completed
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4

        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Set TEST_BASE_URL
        run: echo "TEST_BASE_URL=https://cse210-fa24-group4.github.io/cse210-fa24-group4/" >> $GITHUB_ENV

      - name: Verify TEST_BASE_URL
        run: echo "TEST_BASE_URL is $TEST_BASE_URL"

      - name: Run Playwright tests
        run: npx playwright test --config config/playwright.config.js

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-test-report
          path: playwright-report/
          retention-days: 30
